services:
  backend:
    build: ./services/backend
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/vue_fastapi_tutorial_db
    volumes:
      - ./services/backend:/app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 5000

  db:
    image: postgres
    expose:
      - 5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=vue_fastapi_tutorial_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build: ./services/frontend
    volumes:
      - ./services/frontend:/app
      - /app/node_modules
    ports:
      - 8080:8080

volumes:
  postgres_data:
